Use openjdk-1.8 packages for Fedora 21
Puppet installs on Fedora 21 fail with:

---
Error: /Stage[main]/Jenkins::Slave/Package[java-1.7.0-openjdk-devel]/ensure:
  change from absent to present failed:
   Execution of '/usr/bin/yum -d 0 -e 0 -y list java-1.7.0-openjdk-devel'
    returned 1: Error: No matching Packages to list
---

Fedora 21 has retired openjdk-1.7 for 1.8; see [1]

[1] http://fedoraproject.org/wiki/Changes/Java8

Change-Id: I06b6d97000f67d099d9886f75f528a41aa68e8e7