SECURITY-218: Update to latest cli-shutdown.groovy
Update to the latest version of the script:
https://github.com/jenkinsci-cert/SECURITY-218/blob/3b8e932110fd4f0ad74323f73e77f6ce97286b9b/cli-shutdown.groovy

This also removes the previous invalid comments that resulted in
the following error in /var/log/jenkins/jenkins.log:

WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/cli-shutdown.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/var/lib/jenkins/init.groovy.d/cli-shutdown.groovy: 1: expecting '!', found ' ' @ line 1, column 2.
   # taken directly from https://github.com/jenkinsci-cert/SECURITY-218
    ^

1 error

Change-Id: Ief950cffb24229aea8cbcabf62d3339aca6c9630